### ISSUE TITLE
Navigation bar is not properly set for iPhone-X

### ISSUE THREAD

**Issue by JigarPatel1234** [yahoo/YangMingShan#43]
I am using this control in my app and now for ios 11 iPhoneX i am facing problem in navigation bar as it is not properly used in iPhoneX simulator, so can it be possible to fix this issue. Thank you

**Comment by Sunbir** [comment]
I see a similar issue with navigation spacing in general for ios 11. See attached screenshot:

![simulator screen shot - iphone 6s - 2017-09-30 at 12 28 30](https://user-images.githubusercontent.com/1574603/31048860-7f99edc0-a5db-11e7-84ae-b485fcd7baa7.png)

**Comment by drante** [comment]
@Sunbir Have you managed to solve this problem?

**Comment by Sunbir** [comment]
Sorry, I haven't looked into it yet.

**Comment by ZZBHuang** [comment]
It should be fixed on version 2.0.0

**Comment by drante** [comment]
@ZZBHuang I recently updated to version 2.0.0, but now the navigation bar has disappeared completely.
![simulator screen shot - iphone 7 - 2017-10-15 at 01 51 09](https://user-images.githubusercontent.com/8976714/31580306-cca174d2-b14b-11e7-949d-52e9de90cf3f.png)

**Comment by ZZBHuang** [comment]
@drante Could you tell me your developing environment? Like Xcode version, target iOS version on simulator and reproduce flow. I've tried 2.0.0 on iPhone 8 simulator with Xcode 9.0 but got no luck to reproduce your issue. Thanks!

**Comment by drante** [comment]
@ZZBHuang Sure! :)

Xcode version: 9.0
iOS Deployment Target: 10.0

I tried a full reinstall of the pod but the problem still remained. Also, when presenting the image picker, I call _present(imagePickerController, animated: true, completion: nil)_ instead of _self.yms_presentCustomAlbumPhotoView(pickerViewController, delegate: self)_. Not sure if that has anything to do with this, but calling _present()_ has worked fine until now.

**Comment by ZZBHuang** [comment]
@drante Please use yms_presentCustomAlbumPhotoView instead because this version I'd added UINavigationController with YMSPhotoPickerViewController to display navigation bar. If you use present(imagePickerController, animated: true, completion: nil) then you cannot have the navigation bar supported. Thanks for your feedback!

**Comment by ZZBHuang** [comment]
@JigarPatel1234 Please try 2.0.0 and close this issue if your problem solved :)

**Comment by rahulvyas** [comment]
I am also having the same issue on iPhone X.
I am using yms_presentCustomAlbumPhotoView method to show picker

**Comment by ZZBHuang** [comment]
@rahulvyas Hi, does the demo app have the same problem on your iPhone X? You can enter bigger than 1 number to launch yms_presentCustomAlbumPhotoView on demo app.

**Comment by shrimp101** [comment]
I'm trying to install version 2.0.0 but it not success.
Please check my attachment

![screen shot 2018-06-05 at 16 33 51](https://user-images.githubusercontent.com/4330436/40968000-b7738898-68de-11e8-82bf-1a14c91d6030.png)
![screen shot 2018-06-05 at 16 33 59](https://user-images.githubusercontent.com/4330436/40968001-b7b7e88a-68de-11e8-942d-e1eb035a7e21.png)
